---
title: "Viz 1"
author: "Casandra Laney"
date: "2025-09-25"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r}

library(tidyverse)
library(ggridges)

```

Import the weather data

```{r}

library(p8105.datasets)
data("weather_df")

```

Making our first plot
```{r}

ggplot(weather_df, aes(x = tmin, y =tmax)) +
  geom_point()

```

```{r}

weather_df |>
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point()

```

```{r}

ggp_weather_scatterplot =
  weather_df |>
    ggplot(aes(x = tmin, y = tmax)) +
    geom_point()

ggp_weather_scatterplot

```

Check that some rows are missing

```{r}

weather_df |>
  filter(is.na(tmax))

```

## Fancier Scatterplots!

```{r}

weather_df |>
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(aes(color = name, size = prcp), alpha = 0.3) +
  geom_smooth(se = FALSE)

```

Use faceting real quick

```{r}

weather_df |>
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(aes(color = name), alpha = 0.3, size = 0.8) +
  geom_smooth(se = FALSE) +
  facet_grid(. ~ name)

weather_df |>
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(aes(color = name), alpha = 0.3, size = 0.8) +
  geom_smooth(se = FALSE) +
  facet_grid(name ~ .)

```

Let's make a somewhat more interesting scatterplot

```{r}

weather_df |>
  ggplot(aes(x = tmin, y = tmax, color = name, shape = name)) +
  geom_point(aes(size = prcp), alpha = 0.3) +
  geom_smooth(se = FALSE) +
  facet_grid(. ~ name)

```

Learning Assessment

```{r}

weather_df |>
  filter(name == "CentralPark_NY") |> 
  mutate(
    tmax_fahr = tmax * (9 / 5) + 32,
    tmin_fahr = tmin * (9 / 5) + 32) |> 
  ggplot(aes(x =tmin_fahr, y = tmax_fahr)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  facet_grid(. ~ name)

```

```{r}

weather_df |>
  ggplot(aes(x = tmin, y = tmax)) +
  #geom_hex() not using this bc i have to install the package for it
  geom_point(color = "#b22222")
```

## univariate plots

```{r}

weather_df |>
  ggplot(aes(x = tmin)) +
  geom_histogram(color = "white", fill = "green")

weather_df |>
  ggplot(aes(x = tmin, fill = name)) +
  geom_histogram() +
  facet_grid(. ~ name)

```

density plot

```{r}

weather_df |>
  ggplot(aes(x = tmin, fill = name)) +
  geom_density(alpha = 0.2)

```

box plot

```{r}

weather_df |>
  ggplot(aes(x = name, y = tmin)) +
  geom_boxplot(aes(fill = name))

```

violin plot

```{r}

weather_df |>
  ggplot(aes(x = name, y = tmin, fill = name)) +
  geom_violin()

```

ridge plot

```{r}

weather_df |>
  ggplot(aes(x = tmin, y = name, fill = name)) +
  geom_density_ridges(alpha = 0.2)

```

LA univariate plots

```{r}

weather_df |>
  ggplot(aes(x = prcp, fill = name)) +
  geom_density(alpha = 0.2)

weather_df |>
  ggplot(aes(x = prcp, fill = name)) +
  geom_histogram() +
  facet_grid(name ~.)

weather_df |>
  filter(prcp > 5, prcp < 1000) |>
  ggplot(aes(x = prcp, fill = name)) +
  geom_density(alpha = 0.2)

```

Saving plots

```{r}
ggp_weather_violin = 
  weather_df |>
  ggplot(aes(x = name, y = tmin, fill = name)) +
    geom_violin()

ggp_weather_violin

ggsave("violin_plot.pdf", ggp_weather_violin,
       width = 8, height = 6)

```

Embedding plots

```{r, fig.width = 6, fig.height = 4}

ggp_weather_violin

```

